### PR TITLE
fix lama_convert_16_to_8.py in regards to #19

### PR DESCRIPTION
**Pull request by Dorky-Lever**
Fixed the parser arguments so --clobber is recognised. 

Also changed indir from being being multiple directories within main to just taking a single directory as convert_16_bit_to_8bit  is only written for single directories.

### CODE REVIEW

**Comment by nrhorner** [comment]
Hi,

--clobber is working for me

for example, the following processes all files from inputs_dir1 and inputs_dir2

```python
lama_convert_16_to_8.py -i inputs_dir1 inputs_dir2 --clobber
```

Would you mind pasting an example of how you run it?

**Comment by Dorky-Lever** [comment]
Hi Neil, 

I've been calling lama_convert_16_to_8 via command line i.e. 

(base) PS C:\Users\u5823099\lama_walkthroughs\data\population_average> lama_convert_16_to_8 -i inputs inputs2 --clobber
usage: Rescale 16 bit images to 8bit [-h] -i [INDIR [INDIR ...]] [-o OUTDIR]
Rescale 16 bit images to 8bit: error: unrecognized arguments: --clobber

**Comment by Dorky-Lever** [comment]
Should you be able to the call the actual python script (lama_convert_16_to_8.py) from command line? Neither my cluster nor Anaconda works that way. 

I tried explicitly calling the original python script as well (on Anaconda because I edited lama_convert_to_8.py on my cluster) but clobber is still not recognised: 

(base) PS C:\Users\u5823099\lama_walkthroughs\data\population_average> python C:\Users\u5823099\Anaconda3\Lib\site-packages\lama\utilities\lama_convert_16_to_8.py -i inputs --clobber
usage: Rescale 16 bit images to 8bit [-h] -i [INDIR [INDIR ...]] [-o OUTDIR]
Rescale 16 bit images to 8bit: error: unrecognized arguments: --clobber

**Comment by nrhorner** [comment]
Can you check to see if this is still an issue on the dev branch?

**Comment by Dorky-Lever** [comment]
Hi Neil, 

This is not an issue on the dev branch, I'll close the issue.

**Pull request closed without merging**
